# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd912649f1a064989f7b19c9b8656f56ab82d7e72c0e7c242bcbbb7c3eb8b4d5aee4d42773c8b791dd6d99dd801353c7943aa6c8488cfd8fa4103a1ca050f2c7

test:
  secret_key_base: 065a9c0e715c9216003561abab8d3084a327ae85631ce0bf8ccddaca8e7d92966948323f2de805477ceac00ec98c0b0a955f525c190b523d39975cd7706b3be2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
